server:
  port: 8761

spring:
  application:
    name: discovery-service  # Good, but make sure this matches everywhere

eureka:
  instance:
    hostname: discovery  # Matches container name - good
    prefer-ip-address: false
  client:
    register-with-eureka: false  # Correct for standalone server
    fetch-registry: false       # Correct for standalone server
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # Self-reference
  server:
    enable-self-preservation: false  # For testing
    eviction-interval-timer-in-ms: 4000

management:
  endpoints:
    web:
      exposure:
        include: health,info