spring:
  cloud:
    gateway:
      routes:
        - id: analyse-facture-ms
          uri: lb:http://ANALYSE-FACTURE-MS
          predicates:
            - Path=/analyse-facture/**

        - id: stockage-facture-ms
          uri: lb:http://STOCKAGE-FACTURE-MS
          predicates:
            - Path=/stockage-facture/**
server:
  port: 8100
