spring:
  cloud:
    gateway:
      routes:
        - id: analyse-facture-ms
          uri: lb:http://ANALYSE-FACTURE-MS
          predicates:
            - Path=/analyse-facture/**

        - id: stockage-facture-ms
          uri: lb:http://STOCKAGE-FACTURE-MS
          predicates:
            - Path=/api/v1/stockage-facture/**

        - id: user-ms
          uri: lb:http://USER-MS
          predicates:
            - Path=/api/v1/user-ms/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8079/realms/portnet"
server:
  port: 8100




logging:
  level:
    root: info
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG