spring:
  cloud:
    gateway:
      routes:
        - id: analyse-facture-ms
          uri: lb://ANALYSE-FACTURE-MS
          predicates:
            - Path=/api/v1/analyse-facture/**
        - id: stockage-facture-ms
          uri: lb://STOCKAGE-FACTURE-MS
          predicates:
            - Path=/api/v1/stockage-facture/**