spring:
  cloud:
    gateway:
      routes:
        - id: stockage-facture-ms
          uri: lb://stockage-facture-ms
          predicates:
            - path=/api/v1/stockage-facture/**
        - id: analyse-facture-ms
          uri: lb://analyse-facture-ms
          predicates:
            - path=/api/v1/analyse-facture/**
