spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/factureDB
    username: postgres
    password: postgres
  sql:
    init:
      platform: postgres
      mode: always
server:
  port: 8083
  
springdoc:
  swagger-ui:
    path: /api/v1/stockage-facture/swagger-ui.html