spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  sql:
    init:
      platform: postgres
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/portnet
server:
  port: 8089